name: voice_access
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  path: ^1.8.3
  sqflite: ^2.3.0
  audioplayers: ^5.2.0
  # record: ^5.0.1
  flutter_sound: ^9.2.13
  permission_handler: ^11.0.1
  curved_text: ^0.2.0
  flutter_tts: ^3.8.5
  just_audio: ^0.9.36
  
  
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/appPhoto.jfif"    

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Teddy_under_rainbow.jfif
    - assets/apple.jfif
    - assets/appPhoto.jfif
    - assets/listening.jfif
    - assets/dog.jfif
    - assets/shapes.jfif
    - assets/car.jfif
    - assets/colors.jfif
    - assets/sad.jfif
    - assets/clouds.jfif 
    - assets/animals.jfif
    - assets/cat.jfif
    - assets/lion.jfif
    - assets/monkey.jfif
    - assets/fruits.jfif
    - assets/orange.jfif
    - assets/strawbelly.jfif
    - assets/banana.jfif
    - assets/yellow.jfif
    - assets/pink.jfif
    - assets/blue.jfif
    - assets/red.jfif
    - assets/motorbike.jfif
    - assets/bicycle.jfif
    - assets/truck.jfif
    - assets/vehicles.jfif
    - assets/circle.jfif
    - assets/square.jfif
    - assets/triangle.jfif
    - assets/star.jfif
    - assets/talk.jfif
    - assets/am listening.jpg
    - assets/appPhoto.jfif
    - assets/ear.jfif
    - assets/mouth.jfif
    - assets/alphabet.jfif
    - assets/A.jfif
    - assets/B.jfif
    - assets/C.jfif
    - assets/D.jfif
    - assets/E.jfif
    - assets/F.jfif
    - assets/G.jfif
    - assets/H.jfif
    - assets/I.jfif
    - assets/J.jfif
    - assets/K.jfif
    - assets/L.jfif
    - assets/M.jfif
    - assets/N.jfif
    - assets/O.jfif
    - assets/P.jfif
    - assets/Q.jfif
    - assets/R.jfif
    - assets/S.jfif
    - assets/T.jfif
    - assets/U.jfif
    - assets/V.jfif
    - assets/W.jfif
    - assets/X.jfif
    - assets/Y.jfif
    - assets/Z.jfif
    - assets/VonnieTalk.jpg
    - assets/BackGround2.jpg


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
